### ISSUE TITLE
iGibson installation failure

### ISSUE THREAD

**Issue by vk-mittal14** [ChengshuLi/HRL4IN#4]
iGibson hrl4in branch Installation failed.
  
While following the provided installation instruction, iGibson installation failed while installing `pyopengl-accelerate`.

**Comment by ChengshuLi** [comment]
Sorry for my late reply. Could you describe your installation process and error messages?

**Comment by vk-mittal14** [comment]
@ChengshuLi Thanks for the reply!  
Recently, I removed the code that cause the above error so currently I can not reproduce the same error again. However, I just tried installing igibson for this repo again and now I am getting a different error causing igibson installation failure, please check it out. 

**Instructions used:** 
```
git clone --recursive https://github.com/StanfordVL/iGibson.git
cd iGibson
git checkout archive/hrl4in
pip install -e .
```
**Error:** 

```
    ERROR: Command errored out with exit status 1:
     command: /home/vkmittal14/miniconda3/envs/hrl4in-igibson/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/vkmittal14/WORKSPACE/TUD/HRL_igibon/iGibson/setup.py'"'"'; __file__='"'"'/home/vkmittal14/WORKSPACE/TUD/HRL_igibon/iGibson/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/vkmittal14/WORKSPACE/TUD/HRL_igibon/iGibson/
    Complete output (46 lines):
    running develop
    running egg_info
    writing gibson2.egg-info/PKG-INFO
    writing dependency_links to gibson2.egg-info/dependency_links.txt
    writing requirements to gibson2.egg-info/requires.txt
    writing top-level names to gibson2.egg-info/top_level.txt
    reading manifest file 'gibson2.egg-info/SOURCES.txt'
    writing manifest file 'gibson2.egg-info/SOURCES.txt'
    running build_ext
    CMake Error at CMakeLists.txt:13 (add_subdirectory):
      The source directory
    
        /home/vkmittal14/WORKSPACE/TUD/HRL_igibon/iGibson/gibson2/core/render/pybind11
    
      does not contain a CMakeLists.txt file.
    
    
    -- Configuring incomplete, errors occurred!
    See also "/home/vkmittal14/WORKSPACE/TUD/HRL_igibon/iGibson/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/vkmittal14/WORKSPACE/TUD/HRL_igibon/iGibson/setup.py", line 115, in <module>
        tests_require=[],
      File "/home/vkmittal14/miniconda3/envs/hrl4in-igibson/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/vkmittal14/miniconda3/envs/hrl4in-igibson/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/vkmittal14/miniconda3/envs/hrl4in-igibson/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/vkmittal14/miniconda3/envs/hrl4in-igibson/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/vkmittal14/miniconda3/envs/hrl4in-igibson/lib/python3.6/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/vkmittal14/miniconda3/envs/hrl4in-igibson/lib/python3.6/site-packages/setuptools/command/develop.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "/home/vkmittal14/miniconda3/envs/hrl4in-igibson/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/vkmittal14/miniconda3/envs/hrl4in-igibson/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/vkmittal14/WORKSPACE/TUD/HRL_igibon/iGibson/setup.py", line 38, in run
        self.build_extension(ext)
      File "/home/vkmittal14/WORKSPACE/TUD/HRL_igibon/iGibson/setup.py", line 72, in build_extension
        subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
      File "/home/vkmittal14/miniconda3/envs/hrl4in-igibson/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/home/vkmittal14/WORKSPACE/TUD/HRL_igibon/iGibson/gibson2/core/render', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/vkmittal14/WORKSPACE/TUD/HRL_igibon/iGibson/gibson2/core/render/mesh_renderer', '-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/home/vkmittal14/WORKSPACE/TUD/HRL_igibon/iGibson/gibson2/core/render/mesh_renderer/build', '-DPYTHON_EXECUTABLE=/home/vkmittal14/miniconda3/envs/hrl4in-igibson/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/vkmittal14/miniconda3/envs/hrl4in-igibson/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/vkmittal14/WORKSPACE/TUD/HRL_igibon/iGibson/setup.py'"'"'; __file__='"'"'/home/vkmittal14/WORKSPACE/TUD/HRL_igibon/iGibson/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

**Comment by fxia22** [comment]
sorry, we updated the installation instruction again just now, can you try again?

**Comment by vk-mittal14** [comment]
Thanks for resolving the installation issues, it's working now. 

I have 2 more small doubts: 

1. In this HRL4IN code I found `train_hrl_relmogen.py`, is this file contains the code you used for the "ReLMoGen: Integrating Motion Generation in Reinforcement Learning for Mobile Manipulation" paper. 
2. Also this `train_hrl_relmogen.py` imports an RL env `from gibson2.envs.motion_planner_env import MotionPlanningBaseArmHRL4INEnv`. If you have open-sourced this environment source code, can you please tell me where I can find that?

**Comment by ChengshuLi** [comment]
Could you please use the `master` branch instead of `rss_dev` branch?

`train_hrl_relmogen.py` is an internal development branch that we used to compare with ReLMoGen in that paper. Please ignore it.

**Comment by vk-mittal14** [comment]
Cool! Thanks for the support.
